# Generated by Django 4.2.13 on 2026-05-31 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('age', models.IntegerField(verbose_name='Yaş')),
                ('city', models.CharField(max_length=100, verbose_name='Yaşadığım Şehir')),
                ('profession', models.CharField(max_length=100, verbose_name='Mesleğim')),
                ('linkedin_url', models.URLField(verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(verbose_name='Github URL')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about_photos/', verbose_name='Güncel Fotoğraf')),
            ],
            options={
                'verbose_name': 'Hakkımda Bilgisi',
                'verbose_name_plural': 'Hakkımda Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Teknik Bilgi', 'Teknik Bilgi'), ('Teknik Olmayan Bilgi', 'Teknik Olmayan Bilgi'), ('Araştırmalarım', 'Araştırmalarım'), ('Hobilerim', 'Hobilerim'), ('Okuduğum Kitaplar', 'Okuduğum Kitaplar')], max_length=50, verbose_name='Eklenecek Bölüm')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Görsel')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana Sayfada Öne Çıkar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Bağlı Olduğu Kategori')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
            },
        ),
    ]
