"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bk7x0z)j=fqw$c&r=jcil+1qdt&-u$!m$tkoqvtxr1kwx^ftub'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # BİZİM EKLEDİKLERİMİZ:
    'rest_framework',
    'corsheaders',
    'api',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# MASAÜSTÜNDEKİ YEREL MYSQL (XAMPP) AYARLARIMIZ
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog_db',      # phpMyAdmin'de açtığımız isim
        'USER': 'root',         # XAMPP varsayılan kullanıcısı
        'PASSWORD': '',         # XAMPP varsayılan şifresi boştur
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOW_ALL_ORIGINS = True

JAZZMIN_SETTINGS = {
    # Panelin sekme başlığı
    "site_title": "Berk İğmar Admin",
    
    # Giriş ekranındaki büyük başlık
    "site_header": "Dijital Yönetim Paneli",
    
    # Sol üst köşedeki marka adı
    "site_brand": "Berk İğmar.",
    
    # Giriş ekranındaki hoş geldin yazısı
    "welcome_sign": "Yönetim Paneline Hoş Geldiniz",
    
    # Telif hakkı yazısı
    "copyright": "Berk İğmar",
    
    # Sol menüdeki ikonlar (Sınıfların yanına havalı FontAwesome ikonları ekler)
    "icons": {
        "auth.Group": "fas fa-users",
        "auth.User": "fas fa-user",
        "api.Post": "fas fa-pen-nib", # Buradaki 'api.Post' senin app ve model adın, ona göre değiştirebilirsin
    },
    
    # Karanlık Mod / Aydınlık Mod butonu gelsin mi?
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "dark_mode_theme": None,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'